### PR TITLE
Update the Reddit code block for retrieving token

### PR DESCRIPTION
**Pull request by mickr**
## Changes 💡
Update the Reddit code block since it doesn't conform to next-auth v4.

## Affected issues 🎟
Not sure

### CODE REVIEW

**Comment by mickr** [comment]
That's strange, Typescript throws errors if I remove properties when using this object.

**Comment by balazsorban44** [comment]
Should absolutely not be necessary. Please open a bug report with a reproduction on the core repo otherwise, please update this PR as suggested. 🙏

**Comment by balazsorban44** [comment]
@mickr are you still interested in fixing this, or should I push the changes?

**Comment by mickr** [comment]
Sorry, I've been busy. I'll fix up the PR today

**Pull request closed without merging**
