### PR TITLE
Delete typeorm-custom-models.md

### PR DESCRIPTION
**Pull request by balazsorban44**
This file should have been removed as for v4, custom models is documented under https://next-auth.js.org/adapters/typeorm#custom-models

### CODE REVIEW

**Review by ndom91 — APPROVED** [review]
Nice good call!

**Comment by balazsorban44** [comment]
seems to be some build issues. the old docs still point to that page. 😕. I dont want docusaurus to ignore broken links though, how could we fix that? 🤔

**Comment by ndom91** [comment]
@balazsorban44 We can use a vercel.json rewrite/redirect. Not sure if the docusaurus broken link checker think would pick up on it, but it's definitely worth a shot.

**Comment by balazsorban44** [comment]
I decided to just manually override the broken links.

**Pull request merged**
