### PR TITLE
Add note about the String type for MySQL in Prisma

### PR DESCRIPTION
**Pull request by 2color**
## Changes 💡

Add note about the underlying database type for String in Prisma.

Related tweet: https://twitter.com/aidevv_in/status/1471147949136637952

### CODE REVIEW

**Review by balazsorban44 — CHANGES_REQUESTED** [review]
Thank you, appreciate this!

I think we should put this higher up, eg. in the models page. Other adapters might have this issue as well.

https://next-auth.js.org/adapters/models

Start with something general, like 
"some providers' returned values exceed our default lengths, but it's easy to mitigate by tweaking your schema. For example,... " and then you can give a Prisma example about the `id_token`

**Comment by 2color** [comment]
Yeah it'd be good to update the UML diagram on the Models page and maybe add a note. Do you have the source [for it](https://next-auth.js.org/assets/images/nextauth_v4_schema-9d6746cfdef30cb1a4c573edb0cc8070.png)?

For the Prisma page, I would also add `@db.Text` to the sample Prisma schema so that it's explicit for both MySQL and PostgreSQL and that beginners get it right the first time.

**Comment by balazsorban44** [comment]
Sounds good. @ndom91 might have the source. We added [Mermaid](https://mermaid-js.github.io/mermaid/#/) support though, it would be awesome to convert that image. 🙏 👀

Feel free to update the default schema recommendation.

**Comment by ndom91** [comment]
Hey yall, opened a PR updating that image to mermaid text here (https://github.com/nextauthjs/docs/pull/182).

**Comment by Katli95** [comment]
Hey guys, not to block this from merging just saw that the original issue was closed. I ran into the same thing using the `AzureADProvider` with the `PrismaAdapter`. Upon raising the maxLength to 5.000 inspection revealed that the `access_token` from Azure is a whopping 2167 chars in my case, might very well be longer for others.

Do you want me to open this as a seperate issue?

**Comment by balazsorban44** [comment]
this won't be a provider specific update (ideally not even Prisma-only either)

we will recommend the same schema for all providers

**Review by balazsorban44 — APPROVED** [review]

**Comment by balazsorban44** [comment]
I merged this as I've seen a lot of confusion with Prisma (being as popular as it is :tada:) on Twitter and other places, it's good that we inform people about the schema as quickly as possible. We will take measures to bring this information to other adapters later. Thanks you @2color!

**Pull request merged**
