### PR TITLE
Add neo4j adapter page and links in sidebar and overview page

### PR DESCRIPTION
**Pull request by EarthlingDavey**
## Changes 💡

Add neo4j adapter page and links in sidebar and overview page

## Affected issues 🎟

https://github.com/nextauthjs/adapters/pull/186

### CODE REVIEW

**Comment by EarthlingDavey** [comment]
Mods, please don't merge in until https://github.com/nextauthjs/adapters/pull/186 is completed.

**Review by balazsorban44 — APPROVED** [review]
LGTM! Really appreciate your patince!

Let's wait with the merge until https://github.com/nextauthjs/adapters/pull/314 is merged, feel free to comment on that PR @EarthlingDavey. I'll have a look as well together with @ndom91 soon.

**Comment by balazsorban44** [comment]
Is this good to go from your sid @EarthlingDavey?

**Comment by EarthlingDavey** [comment]
Yes, absolutely.

**Review by balazsorban44 — APPROVED** [review]

**Pull request merged**
