### PR TITLE
Update auth0 provider docs to point to beta branch

### PR DESCRIPTION
**Pull request by callmenick**
## Changes 💡

Beta docs are pointing to the v3 GH code ref. This PR updates the link to the beta branch

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
I understand the confusion here, but we either update ALL the providers and other possible references to the main branch that should be beta as well AND remember to update everything back when v4 hits stable, or we just let it be. 🤷‍♂️. What do you think?

**Comment by balazsorban44** [comment]
I might agree about this after all, see #31

Could you maybe update all the links to providers, not just for Auth0? Then I would be happy to merge this!

**Comment by callmenick** [comment]
Yeah that's a good point. I'll take a look through

**Comment by balazsorban44** [comment]
This should be done holistically, although we will release a stable v4 in ~2 weeks, maybe there is no point in this PR anymore. Thanks anyway!

**Pull request closed without merging**
