### PR TITLE
docs(credentials): Add `type`, `id` and remove 1 space on credentials docs

### PR DESCRIPTION
**Pull request by mrzmyr**
Add `type`, `id` and remove 1 space

### CODE REVIEW

**Review by balazsorban44 — COMMENTED** [review]
what's the intention behind this? those aren't necessary, I can agree to the space removal

**Comment by mrzmyr** [comment]
The example code only works if `type` and `id` is set as they are required. If you just copy and paste, the code doesn't work right away. After this change it works with a copy paste :)

**Comment by balazsorban44** [comment]
don't follow. those aren't required fields when you are overriding the default options.

**Comment by mrzmyr** [comment]
Ah now I see what you mean. The defaults are already defined in this file: https://github.com/nextauthjs/next-auth/blob/main/src/providers/credentials.js

Then this can be closed. Sorry for the irritation. :)

**Comment by balazsorban44** [comment]
No problem, I'm happy we cleared it up!

**Pull request closed without merging**
